### ISSUE TITLE
"npm install" fails due to unmet webpack dependency

### ISSUE THREAD

**Issue by jdmcnair** [yunity/foodsaving-frontend#526]
The package.json file calls for webback ^3.0.0, but this doesn't meet the peer dependency requirements of karma-webpack@2.0.3, which is loaded for the karma-webpack ^2.0.0 dependency:

`npm WARN karma-webpack@2.0.3 requires a peer of webpack@^1.1.0 || ^2 || ^2.1.0-beta.0 || ^2.2.0-rc.0 but none was installed.`

The same goes for the `html-webpack-plugin@2.28.0` dependency.

The package file needs compatible versions of `webpack`, `karma-webpack`, and `html-webpack-plugin`.

**Comment by tiltec** [comment]
Can you still run `npm run dev`? It works for me.

We have long used formally incompatible packages. E.g. using angular 1.6 while angular-material still required angular 1.5. There wasn't any problem in development or production, other than those npm warnings. Would be nice to selectively supress them.

**Comment by tiltec** [comment]
I did a small update of the new `package-lock.json` file and ran `npm install && npm run dev` in a freshly cloned repo, it works fine here. Can you try with newest `master`?

**Comment by tiltec** [comment]
Depending on the machine I run it on, `npm run dev` also fails... no idea. What do I need to change?
The last system complained about missing `babel-generator`.

```
(venv-3.5.3) ubuntu@box606:~/foodsaving-e2e/foodsaving-frontend$ npm install
removed 3 packages and updated 447 packages in 20.075s
(venv-3.5.3) ubuntu@box606:~/foodsaving-e2e/foodsaving-frontend$ npm run dev

> foodsaving-frontend@0.0.1 dev /home/ubuntu/foodsaving-e2e/foodsaving-frontend
> test -f .env && env $(cat .env) gulp || gulp

[21:06:00] Requiring external module babel-register
module.js:487
    throw err;
    ^

Error: Cannot find module 'babel-generator'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ubuntu/foodsaving-e2e/foodsaving-frontend/node_modules/istanbul-lib-instrument/dist/instrumenter.js:25:23)
    at Module._compile (module.js:569:30)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/ubuntu/foodsaving-e2e/foodsaving-frontend/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
[21:06:00] Requiring external module babel-register
module.js:487
    throw err;
    ^

Error: Cannot find module 'babel-generator'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ubuntu/foodsaving-e2e/foodsaving-frontend/node_modules/istanbul-lib-instrument/dist/instrumenter.js:25:23)
    at Module._compile (module.js:569:30)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/ubuntu/foodsaving-e2e/foodsaving-frontend/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
```

**Comment by tiltec** [comment]
I deleted `node_modules` and `package-lock.json`, ran `npm install` and commited the resulting lock file to master: https://github.com/yunity/foodsaving-frontend/commit/ccf18ed34d25e5024252534eb934a6453168d895
Now you should get exactly the same package versions as me.

**Comment by tiltec** [comment]
This should be resolved by now, but please let us know if the problem persists.
